app:
  charset: UTF-8
  debug: false
  defaultRoute: setting.index
  env: production
  key: ""
  theme: homer # homer, inspinia
  title: Admin Panel

auth:
  default: jwt
  drivers:
    jwt:
      algorithm: HS256
      secret: demopass
      refresh_ttl: 1209600 # 2 weeks, in seconds
      ttl: 7200 # 2 hours, in seconds
    oauth2:
      clientId: demoapp
      clientSecret: demopass
      redirectUri: %base_url%
      urlAuthorize: http://brentertainment.com/oauth2/lockdin/authorize
      urlAccessToken: http://brentertainment.com/oauth2/lockdin/token
      urlResourceOwnerDetails: http://brentertainment.com/oauth2/lockdin/resource

db:
  driver: pdo_mysql
  user: forge
  password: ""
  host: localhost
  port: 3306
  dbname: forge
  unix_socket:
  charset: utf8
  driverOptions:
    1002: SET NAMES utf8
  prefix: tbl_

multitenant:
  enabled: false
  keymap: ApplicationKey

orm:
  cache:
    provider: array
    file:
      directory: %base_path%/storage/framework/cache
      extension: .doctrinecache.data
    redis:
      host: 127.0.0.1
      port: 6379
      dbindex: 1
  custom_types:
    bool: Chaos\Doctrine\Types\BoolType
    double: Chaos\Doctrine\Types\DoubleType
    int: Chaos\Doctrine\Types\IntType
    mediumint: Chaos\Doctrine\Types\MediumIntType
    timestamp: Chaos\Doctrine\Types\TimestampType
    tinyint: Chaos\Doctrine\Types\TinyIntType
  metadata:
    driver: annotation
    paths:
      - %base_path%/modules/Account/Entities
      - %base_path%/modules/System/Entities
    simple: false
  proxy_classes:
    auto_generate: 0
    directory: %base_path%/storage/framework/proxies
    namespace:
  default_repository: Doctrine\ORM\EntityRepository
  sql_logger:
  walkers:
    doctrine.customOutputWalker: Chaos\Doctrine\Walkers\CustomOutputWalker

session:
  cookie: chaos
  domain:

paths:
  uploads: %base_path%/public/uploads
  api: %base_path%/public/api

urls:
  reset: %base_url%/#/reset?k=
