db:
  default: mysql
  connections:
    mysql:
      driver: pdo_mysql
      host: localhost
      port: 3306
      dbname: forge
      user: forge
      password:
      unix_socket:
      charset: utf8
      prefix:
